server:
    port : 8006
    
spring:
    application:
            name: CLOUD_CONFIG_SERVER
            
    cloud:      config:        server:            git:              uri: https://github.com/Sweta2678/config-server
              clone-on-start : true
                 
  